s3:
  enabled: true

smtp:
  # Active ou non l'installation du serveur SMTP
  enabled: false

  ingress:
    enabled: true
#    hostOverride: mailhog.example.com

  auth:
    enabled: true
    existingSecret: ""
    fileName: auth.txt
    fileContents: "Ym9iOiQyYSQwNCRRN1VwdmQvWUlwck5DcExsUHpFQ2VlRnZrVlI1RVhKbG1uZjZ4S050ZHlXSnJoeW1hNUhlaQ==" # format user:password (où password est bcrypted) le tout en base64

passage2:
  enabled: true
  reverseproxy:
    hostname: mellon.example.com
    proxy:
      rules: |-
        # demo app
        ProxyPass /whoami "http://whoami-svc:8080/"
        ProxyPassReverse /whoami "http://whoami-svc:8080"
        #Example
        ProxyPass /my-service2 "http://whoami3-svc:80/"
        ProxyPassReverse /my-service2 "http://whoami3-svc:80"

  mockpassage2:
    hostname: passage2.example.com
    adminLogin: admin