---
# Source: dso-chart-ovh/templates/smtp-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: bouchon-smtp-dso-chart-ovh
  labels:
    helm.sh/chart: smtp-dso-chart-ovh-0.0.1
    app.kubernetes.io/name: smtp-dso-chart-ovh
    app.kubernetes.io/instance: bouchon
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
  namespace: "default"
spec:
  type: "ClusterIP"
  ports:
    - name: http
      port: 8025
      protocol: TCP
      targetPort: http
    - name: tcp-smtp
      port: 1025
      protocol: TCP
      targetPort: tcp-smtp
  selector:
    app.kubernetes.io/name: smtp-dso-chart-ovh
    app.kubernetes.io/instance: bouchon
---
# Source: dso-chart-ovh/templates/smtp-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bouchon-smtp-dso-chart-ovh
  labels:
    helm.sh/chart: smtp-dso-chart-ovh-0.0.1
    app.kubernetes.io/name: smtp-dso-chart-ovh
    app.kubernetes.io/instance: bouchon
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
  namespace: "default"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: smtp-dso-chart-ovh
      app.kubernetes.io/instance: bouchon
  template:
    metadata:
      labels:
        app.kubernetes.io/name: smtp-dso-chart-ovh
        app.kubernetes.io/instance: bouchon
    spec:
      serviceAccountName: default
      automountServiceAccountToken: false
      containers:
        - name: smtp-dso-chart-ovh
          image: "docker.io/mailhog/mailhog:latest"
          imagePullPolicy: "IfNotPresent"
          env:
            - name: MH_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - name: http
              containerPort: 8025
              protocol: TCP
            - name: tcp-smtp
              containerPort: 1025
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 1025
            initialDelaySeconds: 10
            timeoutSeconds: 1
          readinessProbe:
            tcpSocket:
              port: 1025
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
