{{- if .Values.passage2.enabled -}}
{{- if .Values.passage2.demoApp.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: debug-tools
  name: debug-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debug-tools
  template:
    metadata:
      labels:
        app: debug-tools
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - image: nicolaka/netshoot
          command: ["sleep"] 
          args: ["infinity"]
          name: debug-tools
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "250m"
      serviceAccount: istio-sa
      securityContext:
        runAsUser: 1000750000 
{{- end -}}
{{- end -}}
