apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gat-{{ .Values.ines.name }}
spec:
  selector:
    istio: egress-gateway
  servers:
    - port:
        number: 80
        name: https-port-for-tls-origination
        protocol: HTTPS
      hosts:
        - {{ .Values.ines.host }}
      tls:
        mode: ISTIO_MUTUAL