apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: eines-{{ .Values.ines.name }}
spec:
  host: egress-gateway.istio-system.svc.cluster.local
  subsets:
    - name: se-ines
      trafficPolicy:
        loadBalancer:
          simple: ROUND_ROBIN
        portLevelSettings:
          - port:
              number: 80
            tls:
              mode: ISTIO_MUTUAL
              sni: {{ .Values.ines.host }}