---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: istio-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - istio-scc
  resources:
  - securitycontextconstraints
  verbs:
  - use

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: istio-role-binding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: istio-role
subjects:
- kind: ServiceAccount
  name: istio-sa
  namespace: {{ .Release.Namespace }}