{{- if .Values.smtp.enabled -}}
{{- if .Values.smtp.ingress.enabled -}}
{{- $fullName := include "mailhog.fullname" . -}}
{{- $apiV1 := false -}}
{{- $apiVersion := "extensions/v1beta1" -}}
{{- if and (.Capabilities.APIVersions.Has "networking.k8s.io/v1") (semverCompare ">= v1.19.0-0" .Capabilities.KubeVersion.Version) -}}
  {{- $apiVersion = "networking.k8s.io/v1" -}}
  {{- $apiV1 = true -}}
{{- else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1" -}}
  {{- $apiVersion = "networking.k8s.io/v1beta1" -}}
{{- else -}}
  {{- $apiVersion = "extensions/v1beta1" -}}
{{- end }}
apiVersion: {{ $apiVersion }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "mailhog.labels" . | nindent 4 }}
  {{- with .Values.smtp.ingress.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.smtp.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.smtp.ingress.ingressClassName }}
  ingressClassName: {{ .Values.smtp.ingress.ingressClassName }}
{{- end }}
  rules:
  {{- range .Values.smtp.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ .path }}
            {{- if $apiV1 }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  name: http
            {{- else }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
            {{- end }}
        {{- end }}
  {{- end }}
{{- end }}
{{- end -}}