{{- if .Values.smtp.enabled -}}
{{- if .Values.smtp.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mailhog.serviceAccountName" . }}
  labels:
    {{- include "mailhog.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
imagePullSecrets:
  {{- toYaml .Values.smtp.serviceAccount.imagePullSecrets | nindent 4 }}
{{- end }}
{{- end -}}