{{- if .Values.passage2.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: passage2-keycloak-auth
data:

  {{- $old_sec := lookup "v1" "Secret" .Release.Namespace "passage2-keycloak-auth" }}

  {{- if or (not $old_sec) (not $old_sec.data) }}
  # Password is not existing, creates a new one
  keycloak-password: {{ randAlphaNum 20 | b64enc }}
  keycloak-admin-login: {{ .Values.passage2.mockpassage2.adminLogin | b64enc }}
  {{ else }}
  # Password already exists, keep previous one
  keycloak-password: {{ index $old_sec.data "keycloak-password" }}
  keycloak-admin-login: {{ index $old_sec.data "keycloak-admin-login" }}
  {{ end }}
{{- end -}}